domenicolafroscia/Deliveboo-laravel

- app/Http/Controllers/Auth/RegisteredUserController.php
- app/Models/User.php
- resources/views/auth/register.blade.php
> fix: RegisteredUserController, model User and blade page Register

- app/Http/Controllers/Admin/DashboardController.php
- app/Models/Restaurant.php
- app/Providers/RouteServiceProvider.php
- resources/views/layouts/admin.blade.php
- routes/web.php
close #1 
need to add controller and crud
> 1 complete restaurants with model controller and route

- resources/views/admin/dashborad.blade.php
> add: dashboard admin page

- app/Http/Controllers/Admim/RestaurantController.php
- database/seeders/RestaurantsTableSeeder.php
- database/seeders/restaurants.csv
- routes/web.php
close #12 (todoo: index, show)
> add: RestaurantsTableSeeder, route, restaurants.csv

- app/Http/Controllers/CategoryController.php
- app/Models/Category.php
- database/migrations/2024_02_19_094351_create_categories_table.php
- routes/web.php
> add: create migration, controller, route and model category

- database/seeders/UsersTableSeeder.php
- database/seeders/users.csv
> add: users seeders and file csv

- database/seeders/CategoriesTableSeeder.php
> add: seeder categories

- app/Models/Category.php
- app/Models/Restaurant.php
- database/migrations/2024_02_19_142804_create_restaurant_category_table.php
> add: pivot table between restaurants and categories

- app/Http/Controllers/Admin/MealController.php
- app/Http/Controllers/Admin/RestaurantController.php
- app/Http/Requests/StoreRestaurantRequest.php
- app/Models/Restaurant.php
- resources/views/admin/dashboard.blade.php
- resources/views/admin/meals/index.blade.php
- resources/views/admin/restaurants/create.blade.php
- resources/views/admin/restaurants/index.blade.php
- resources/views/layouts/admin.blade.php
- routes/web.php
> 14 create restaurant crud create store

- app/Http/Requests/UpdateMealRequest.php
- resources/views/admin/meals/create.blade.php
- resources/views/admin/meals/edit.blade.php
> 21 fix meal controller

- app/Http/Controllers/Admin/RestaurantController.php
- resources/js/app.js
- resources/views/admin/meals/create.blade.php
- resources/views/admin/meals/edit.blade.php
- resources/views/admin/restaurants/create.blade.php
> add: image preview implementation

- resources/views/admin/meals/edit.blade.php
> add: fix edit.blade

- app/Http/Controllers/Admin/MealController.php
- app/Http/Controllers/Admin/TrashController.php
- app/Models/Meal.php
- database/migrations/2024_02_20_133854_add_soft_delete_to_meals_table.php
- resources/views/admin/meals/show.blade.php
- resources/views/admin/restaurants/index.blade.php
- resources/views/admin/trash/index.blade.php
- resources/views/layouts/admin.blade.php
- routes/web.php
> 48 create soft delete for meals

- database/seeders/DatabaseSeeder.php
- database/seeders/MealsTableSeeder.php
- database/seeders/meals.csv
> add: MealsTableSeeder and meals.csv

- resources/js/app.js
- resources/views/admin/trash/index.blade.php
- resources/views/partials/delete_modal.blade.php
> add: delete modal implementation

- resources/js/app.js
- resources/views/admin/meals/edit.blade.php
> fix: preview image in edit meal

- app/Http/Requests/StoreMealRequest.php
- resources/views/admin/meals/create.blade.php
- resources/views/admin/meals/edit.blade.php
> 49 check validation

- app/Http/Controllers/Admin/OrderController.php
> add: check page not found (show)

- app/Models/Order.php
- resources/views/admin/orders/index.blade.php
> add:Show Data order in Index

- resources/views/admin/restaurants/create.blade.php
- resources/views/admin/restaurants/edit.blade.php
> add: fixed: restaurant validations client-side

- app/Http/Controllers/Admin/MealController.php
- app/Http/Requests/StoreMealRequest.php
- app/Http/Requests/UpdateMealRequest.php
- app/Models/Meal.php
- database/migrations/2024_02_19_084428_create_meals_table.php
- database/seeders/MealsTableSeeder.php
- resources/views/admin/meals/create.blade.php
- resources/views/admin/meals/edit.blade.php
> 76 fix update meals controller

- database/seeders/MealsTableSeeder.php
- database/seeders/meals.csv
- resources/views/admin/meals/show.blade.php
> add: image for meals

- database/seeders/RestaurantsTableSeeder.php
- database/seeders/restaurants.csv
> add:images in restaurants table
